{
  pkgs,
  inputs,
  ...
}:
{
  home.packages = [
    pkgs.bat
    pkgs.btop
    pkgs.vesktop
    pkgs.docker-client
    pkgs.docker-compose
    pkgs.fastfetch
    pkgs.ffmpeg
    pkgs.firefox
    pkgs.jq
    pkgs.mpv
    pkgs.nautilus
    pkgs.obs-studio
    pkgs.opencode
    pkgs.pavucontrol
    pkgs.sioyek
    pkgs.spotify
    pkgs.tealdeer
    pkgs.unrar
    pkgs.unzip
    pkgs.xxd
    pkgs.imv
    pkgs.wl-clipboard
    pkgs.wl-mirror
    inputs.herdr.packages.${pkgs.stdenv.hostPlatform.system}.default
    inputs.tuicr.packages.${pkgs.stdenv.hostPlatform.system}.default
    pkgs.yazi
    pkgs.git-filter-repo
    pkgs.duckdb
    pkgs.lazydocker
    pkgs.stremio-linux-shell
    pkgs.dua
    pkgs.pinta
  ];
}
